main: me.Sunny.SpiralCraft.SpiralCraftPlugin
name: SpiralCraft
version: 0.1.3
author: Sunny
api-version: 1.13

commands:
   slash:
   speed:
   generate:
   loot:
   party:
   level:

depend: [ProtocolLib]